from enum import Enum

#------------------
class Fiat(Enum):
    EUR = "EUR",
    USD = "USD",
    GBP = "GBP",
    CHF = "CHF",
    AUD = "AUD",
    BRL = "BRL",
    CAD = "CAD",
    CLP = "CLP",
    CNY = "CNY",
    CZK = "CZK",
    DKK = "DKK",
    HKD = "HKD",
    HUF = "HUF",
    IDR = "IDR",
    ILS = "ILS",
    INR = "INR",
    JPY = "JPY",
    KRW = "KRW",
    MXN = "MXN",
    MRY = "MYR",
    NOK = "NOK",
    NZD = "NZD",
    PHP = "PHP",
    PKR = "PKR",
    PLN = "PLN",
    RUB = "RUB",
    SEK = "SEK",
    SGD = "SGD",
    THB = "THB",
    TRY = "TRY",
    TWD = "TWD",
    ZAR = "ZAR"